# Generated by Django 5.2.5 on 2025-08-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="schedule.service",
                verbose_name="Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Duração do serviço em minutos.",
                verbose_name="Duração em minutos",
            ),
        ),
    ]
