# Generated by Django 5.2.5 on 2025-08-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alter_appointment_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Início do Horário")),
                ("end_time", models.TimeField(verbose_name="Fim do Horário")),
            ],
            options={
                "verbose_name": "Horário Disponível",
                "verbose_name_plural": "Horários Disponíveis",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("day_of_week", "start_time")},
            },
        ),
    ]
