# Generated by Django 5.2.5 on 2025-08-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Concluído em"
            ),
        ),
    ]
