# Generated by Django 5.2.5 on 2025-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_appointment_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="schedule_time",
            field=models.DateTimeField(
                help_text="Já existe um agendamento neste horário.",
                unique=True,
                verbose_name="Data e Hora do Agendamento",
            ),
        ),
    ]
