# Generated by Django 5.2.5 on 2025-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_alter_appointment_schedule_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="schedule_time",
            field=models.DateTimeField(
                error_messages={
                    "unique": "Já existe um agendamento exatamente neste mesmo horário."
                },
                unique=True,
                verbose_name="Data e Hora do Agendamento",
            ),
        ),
    ]
