# Generated by Django 5.2.8 on 2025-12-15 03:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0003_alter_pet_options_alter_breed_description"),
        ("store", "0003_autopromotion_productlot_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        help_text="e.g., 'seasonal_allergy', 'recurring_infection'",
                        max_length=100,
                        verbose_name="Pattern Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Pattern Description")),
                (
                    "confidence_score",
                    models.FloatField(verbose_name="Confidence Score"),
                ),
                ("first_detected", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "related_records",
                    models.JSONField(
                        default=list,
                        help_text="IDs of health records that contributed to this pattern",
                        verbose_name="Related Health Records",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="Suggested actions based on this pattern",
                        verbose_name="AI Recommendations",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_patterns",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Pattern",
                "verbose_name_plural": "Health Patterns",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        size=384,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="all-MiniLM-L6-v2", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Embedding",
                "verbose_name_plural": "Product Embeddings",
            },
        ),
        migrations.CreateModel(
            name="AIGeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("product_description", "Product Description"),
                            ("product_title", "Product Title"),
                            ("health_insight", "Health Insight"),
                            ("health_alert", "Health Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="Input Data")),
                (
                    "generated_content",
                    models.TextField(verbose_name="Generated Content"),
                ),
                ("model_used", models.CharField(default="gemini-pro", max_length=100)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "was_accepted",
                    models.BooleanField(default=False, verbose_name="Accepted by User"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="User Feedback"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="pets.pet",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_contents",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generated Content",
                "verbose_name_plural": "AI Generated Contents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "created_at"],
                        name="ai_aigenera_content_29fb01_idx",
                    ),
                    models.Index(
                        fields=["product", "content_type"],
                        name="ai_aigenera_product_98db97_idx",
                    ),
                    models.Index(
                        fields=["pet", "content_type"],
                        name="ai_aigenera_pet_id_3fea90_idx",
                    ),
                ],
            },
        ),
    ]
