# Generated by Django 5.2.5 on 2025-08-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("VACCINE", "Vacina"),
                            ("SURGERY", "Cirurgia"),
                            ("CONSULTATION", "Consulta"),
                            ("NOTE", "Anotação Geral"),
                            ("OWNER_NOTE", "Anotação do Dono"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Registro",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição detalhada do evento (Ex: Vacina V10, Lote XYZ)."
                    ),
                ),
                (
                    "record_date",
                    models.DateField(help_text="Data em que o evento ocorreu."),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Próxima data (ex: revacinação).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Saúde",
                "verbose_name_plural": "Registros de Saúde",
                "ordering": ["-record_date", "-created_at"],
            },
        ),
    ]
