# Generated by Django 5.2.5 on 2025-08-13 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_records_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="description",
            field=models.TextField(
                help_text="Descrição detalhada do evento (Ex: Vacina V10, Lote XYZ).",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="next_due_date",
            field=models.DateField(
                blank=True,
                help_text="Próxima data (ex: revacinação).",
                null=True,
                verbose_name="Próxima Data",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="record_date",
            field=models.DateField(
                help_text="Data em que o evento ocorreu.", verbose_name="Data do Evento"
            ),
        ),
    ]
