# Generated by Django 5.2.5 on 2025-08-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0002_alter_healthrecord_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada do evento (Ex: Vacina V10, Lote XYZ).",
                verbose_name="Descrição",
            ),
        ),
    ]
