# Generated by Django 5.2.5 on 2025-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customer_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=25, verbose_name="Telefone"),
        ),
    ]
