# Generated by Django 5.2.5 on 2025-09-06 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customer_options_alter_customer_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
            },
        ),
    ]
