# Generated by Django 5.2.5 on 2025-08-12 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Raça"
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("DOG", "Cachorro"),
                            ("CAT", "Gato"),
                            ("BIRD", "Pássaro"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Espécie",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Breve descrição e características da raça.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
                "ordering": ["species", "name"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome do Pet")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pets.breed",
                        verbose_name="Raça",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="accounts.customer",
                        verbose_name="Dono",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
    ]
