# Generated by Django 5.2.5 on 2025-08-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customer_options_alter_customer_user"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="accounts.customer",
                verbose_name="Tutor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pet",
            unique_together={("owner", "name")},
        ),
    ]
