# Generated by Django 5.2.5 on 2025-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_owner_alter_pet_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={
                "ordering": ["name"],
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
        migrations.AlterField(
            model_name="breed",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Breve descrição e características da raça.",
                verbose_name="Descrição",
            ),
        ),
    ]
