# Generated by Django 5.2.5 on 2025-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlot",
            name="auto_discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Desconto progressivo por proximidade da validade, gerenciado pelo sistema.",
                max_digits=5,
                verbose_name="Desconto Automático (%)",
            ),
        ),
    ]
