# Generated by Django 5.2.5 on 2025-08-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_productlot_auto_discount_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPromotion",
            fields=[],
            options={
                "verbose_name": "Promoção por Validade",
                "verbose_name_plural": "Promoções por Validade",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.productlot",),
        ),
        migrations.AddField(
            model_name="productlot",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
    ]
